[build-system]
requires = ["setuptools>=45", "setuptools_scm[toml]>=6.2"]
build-backend = "setuptools.build_meta"

[tool.setuptools_scm]
write_to = "src/metaeditor_safetensors/_version.py"
version_scheme = "guess-next-dev"
local_scheme = "dirty-tag"
