[tool.poetry]
name = "metaeditor_safetensors"
version = "1.0.0"
description = "Metadata editor for safetensors"
authors = ["KPandaK"]

[tool.poetry.dependencies]
python = "^3.10"

packages = [
    { include = "metaeditor_safetensors", from = "src" }
]

[build-system]
requires = ["poetry-core>=1.0.0"]
build-backend = "poetry.core.masonry.api"