name: CI

on:
  pull_request:
    branches: [main, dev]
  push:
    branches: [main, dev]

permissions:
  contents: write
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Check Code Quality
        uses: astral-sh/ruff-action@v3
        with:
          src: "."
          args: "check --output-format=github"
      
      - name: Verify Code Formatting
        uses: astral-sh/ruff-action@v3
        with:
          src: "."
          args: "format --check --diff"
      
      - name: Check Types with mypy
        run: python -m mypy .

  test-linux:
    needs: lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libegl1 libegl-mesa0 libxkbcommon-x11-0 libxcb-icccm4 libxcb-image0 libxcb-keysyms1 libxcb-randr0 libxcb-render-util0 libxcb-xinerama0 libfontconfig1 libxrender1 libxss1 libglib2.0-0 xvfb
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Run tests with coverage
        run: |
          xvfb-run -a python -m coverage run -m unittest discover tests -v
          xvfb-run -a python -m coverage html
        env:
          QT_QPA_PLATFORM: offscreen
      
      - name: Coverage Comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test-other:
    runs-on: ${{ matrix.os }}
    needs: lint
    strategy:
      matrix:
        os: [macos-latest, windows-latest]
        python-version: ["3.10", "3.11", "3.12"]
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Run tests
        run: |
          python -m unittest discover tests -v
        env:
          QT_QPA_PLATFORM: offscreen
