name: Lint

on:
  pull_request:
    branches: [main, dev]

permissions:
  contents: read
  pull-requests: write

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"
          cache: 'pip'
      
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -e .[dev]
      
      - name: Check Code Quality
        uses: astral-sh/ruff-action@v3
        with:
          src: "."
          args: "check --output-format=github"
      
      - name: Verify Code Formatting
        uses: astral-sh/ruff-action@v3
        with:
          src: "."
          args: "format --check --diff"
      
      - name: Check Types with mypy
        run: python -m mypy .
