name: Security Scan

on:
  push:
    branches: [ master, dev ]
    paths:
      - 'requirements*.txt'
      - 'pyproject.toml'
  pull_request:
    branches: [ master, dev ]
    paths:
      - 'requirements*.txt' 
      - 'pyproject.toml'
  schedule:
    # Run weekly on Sundays at 6 AM UTC
    - cron: '0 6 * * 0'

jobs:
  security:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Set up Python 3.10
      uses: actions/setup-python@v5
      with:
        python-version: '3.10'
    
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install safety bandit
        pip install -r requirements.txt
        pip install -r requirements-dev.txt
    
    - name: Run Safety check for known vulnerabilities
      run: |
        safety check --json || true
    
    - name: Run Bandit security linter
      run: |
        bandit -r metaeditor_safetensors -f json || true